const data = [
  {
    id: 1,
    dept: 'Management',
    task: '13',
    inProgress: 12,
    inPipeLine: 32,
    review: 56,
    unassigned: 16,
    Performance: '76',
    subRows: [
      {
        id: 1,
        dept: 'Management',
        task: '13',
        inProgress: 12,
        inPipeLine: 32,
        review: 56,
        unassigned: 16,
        Performance: '76',
        subSubRows: [
          {
            id: 1,
            status: 'In Progress',
            task: 'First Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'amit',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 2,
            status: 'In Pipeline',
            task: 'Second Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 3,
            status: 'Unassigned',
            task: 'Third Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 4,
            status: 'For Review',
            task: 'Fourth Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 5,
            status: 'In Progress',
            task: 'Fifth Task',
            assignedTo: 'amit',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
        ],
      },
    ],
  },
  {
    id: 2,
    dept: 'Research',
    task: '43',
    inProgress: 42,
    inPipeLine: 32,
    review: 56,
    unassigned: 16,
    Performance: '46',
    subRows: [
      {
        id: 1,
        dept: 'Management',
        task: '13',
        inProgress: 12,
        inPipeLine: 32,
        review: 56,
        unassigned: 16,
        Performance: '76',
        subSubRows: [
          {
            id: 1,
            status: 'In Progress',
            task: 'First Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 2,
            status: 'In Pipeline',
            task: 'Second Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 3,
            status: 'Unassigned',
            task: 'Third Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 4,
            status: 'For Review',
            task: 'Fourth Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 5,
            status: 'In Progress',
            task: 'Fifth Task',
            assignedTo: 'amit',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
        ],
      },
    ],
  },
  {
    id: 3,
    dept: 'Marketing',
    task: '13',
    inProgress: 12,
    inPipeLine: 32,
    review: 56,
    unassigned: 16,
    Performance: '76',
    subRows: [
      {
        id: 1,
        dept: 'Management',
        task: '13',
        inProgress: 12,
        inPipeLine: 32,
        review: 56,
        unassigned: 16,
        Performance: '76',
        subSubRows: [
          {
            id: 1,
            status: 'In Progress',
            task: 'First Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 2,
            status: 'In Pipeline',
            task: 'Second Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 3,
            status: 'Unassigned',
            task: 'Third Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 4,
            status: 'For Review',
            task: 'Fourth Task',
            assignedTo: 'amit',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 5,
            status: 'In Progress',
            task: 'Fifth Task',
            assignedTo: 'amit',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'aditya',
            startDate: '12/7/2024',
            endDate: '14/7/2024',
          },
        ],
      },
    ],
  },
  {
    id: 4,
    dept: 'TeamBuilding',
    task: '13',
    inProgress: 12,
    inPipeLine: 32,
    review: 56,
    unassigned: 16,
    Performance: '73',
    subRows: [
      {
        id: 4,
        dept: 'Marketing',
        task: '22',
        inProgress: 10,
        inPipeLine: 20,
        review: 40,
        unassigned: 12,
        Performance: '80',
        subSubRows: [
          {
            id: 1,
            status: 'In Progress',
            task: 'First Task',
            assignedTo: 'lisa',
            impact: 'high',
            completeWithin: 'month',
            assignee: 'daniel',
            startDate: '3/7/2024',
            endDate: '3/8/2024',
          },
          {
            id: 2,
            status: 'In Pipeline',
            task: 'Second Task',
            assignedTo: 'lisa',
            impact: 'medium',
            completeWithin: 'month',
            assignee: 'daniel',
            startDate: '3/7/2024',
            endDate: '3/8/2024',
          },
          {
            id: 3,
            status: 'Unassigned',
            task: 'Third Task',
            assignedTo: 'lisa',
            impact: 'low',
            completeWithin: 'week',
            assignee: 'daniel',
            startDate: '3/7/2024',
            endDate: '3/8/2024',
          },
          {
            id: 4,
            status: 'For Review',
            task: 'Fourth Task',
            assignedTo: 'lisa',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'daniel',
            startDate: '3/7/2024',
            endDate: '3/8/2024',
          },
          {
            id: 5,
            status: 'In Progress',
            task: 'Fifth Task',
            assignedTo: 'lisa',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'daniel',
            startDate: '3/7/2024',
            endDate: '3/8/2024',
          },
        ],
      },
    ],
  },
  {
    id: 5,
    dept: 'Finance',
    task: '15',
    inProgress: 11,
    inPipeLine: 35,
    review: 26,
    unassigned: 56,
    Performance: '36',
    subRows: [
      {
        id: 5,
        dept: 'Finance',
        task: '18',
        inProgress: 8,
        inPipeLine: 15,
        review: 20,
        unassigned: 10,
        Performance: '75',
        subSubRows: [
          {
            id: 1,
            status: 'In Progress',
            task: 'First Task',
            assignedTo: 'mark',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'sophie',
            startDate: '2/7/2024',
            endDate: '9/7/2024',
          },
          {
            id: 2,
            status: 'In Pipeline',
            task: 'Second Task',
            assignedTo: 'mark',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'sophie',
            startDate: '2/7/2024',
            endDate: '9/7/2024',
          },
          {
            id: 3,
            status: 'Unassigned',
            task: 'Third Task',
            assignedTo: 'mark',
            impact: 'low',
            completeWithin: 'week',
            assignee: 'sophie',
            startDate: '2/7/2024',
            endDate: '9/7/2024',
          },
          {
            id: 4,
            status: 'For Review',
            task: 'Fourth Task',
            assignedTo: 'mark',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'sophie',
            startDate: '2/7/2024',
            endDate: '9/7/2024',
          },
          {
            id: 5,
            status: 'In Progress',
            task: 'Fifth Task',
            assignedTo: 'mark',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'sophie',
            startDate: '2/7/2024',
            endDate: '9/7/2024',
          },
        ],
      },
    ],
  },
  {
    id: 6,
    dept: 'Human Resource',
    task: '12',
    inProgress: 52,
    inPipeLine: 12,
    review: 56,
    unassigned: 22,
    Performance: '43',
    subRows: [
      {
        id: 6,
        dept: 'Human Resources',
        task: '12',
        inProgress: 5,
        inPipeLine: 10,
        review: 15,
        unassigned: 5,
        Performance: '70',
        subSubRows: [
          {
            id: 1,
            status: 'In Progress',
            task: 'First Task',
            assignedTo: 'jane',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'david',
            startDate: '7/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 2,
            status: 'In Pipeline',
            task: 'Second Task',
            assignedTo: 'jane',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'david',
            startDate: '7/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 3,
            status: 'Unassigned',
            task: 'Third Task',
            assignedTo: 'jane',
            impact: 'low',
            completeWithin: 'week',
            assignee: 'david',
            startDate: '7/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 4,
            status: 'For Review',
            task: 'Fourth Task',
            assignedTo: 'jane',
            impact: 'high',
            completeWithin: 'week',
            assignee: 'david',
            startDate: '7/7/2024',
            endDate: '14/7/2024',
          },
          {
            id: 5,
            status: 'In Progress',
            task: 'Fifth Task',
            assignedTo: 'jane',
            impact: 'medium',
            completeWithin: 'week',
            assignee: 'david',
            startDate: '7/7/2024',
            endDate: '14/7/2024',
          },
        ],
      },
    ],
  },
]

export default data
